error500
B2B-Services/quickquotes pull request #1
Opened 2023-03-24 18:07 UTC by Kelvin-Ofili

error500(UI)
error404(under maintenance)(UI)

2023-03-24 23:15 UTC, The-Anomaly requested changes

2023-03-24 23:15 UTC, The-Anomaly commented on src/assets/vectors/navBars.svg
Why is this asset here? What was it used for?

2023-03-24 23:15 UTC, The-Anomaly commented on src/layouts/home/navbar/index.tsx
Going to need you to fix the indentation of your editor. 
Do you use prettier?

2023-03-24 23:15 UTC, The-Anomaly commented on src/router/routeBuilder.ts
No direct changes to this page, but your indentation has affected it.
Please use prettier.

2023-03-24 23:15 UTC, The-Anomaly commented on src/router/routes.ts
Indentation problem. Use prettier.

2023-03-24 23:15 UTC, The-Anomaly commented on yarn.lock
How come there are changes to the lock file?

2023-03-25 13:17 UTC, Kelvin-Ofili commented
Hi Favour,

My bad. It was for the nav-bar of the Unsupported screen size page, but you
told me not to bother about the nav-bar. I forgot to remove it.

Yes, I use prettier.
To trigger the prettier action, I just need to press ctrl s, no? Will do
that.

For the yarn.lock issue, I have literally no idea why there are changes in
it. All I remember using Yarn to do was to start up the app at some point.
Maybe that may have caused the change. I will look into it.

I should be done with these within the hour.
Thank you.

On Sat, 25 Mar 2023 at 00:15, Favour Adekogbe ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On src/assets/vectors/navBars.svg
> <https://github.com/B2B-Services/quickquotes/pull/1#discussion_r1148134435>
> :
>
> Why is this asset here? What was it used for?
> ------------------------------
>
> On src/layouts/home/navbar/index.tsx
> <https://github.com/B2B-Services/quickquotes/pull/1#discussion_r1148136522>
> :
>
> Going to need you to fix the indentation of your editor.
> Do you use prettier?
> ------------------------------
>
> On src/router/routeBuilder.ts
> <https://github.com/B2B-Services/quickquotes/pull/1#discussion_r1148136885>
> :
>
> No direct changes to this page, but your indentation has affected it.
> Please use prettier.
> ------------------------------
>
> On src/router/routes.ts
> <https://github.com/B2B-Services/quickquotes/pull/1#discussion_r1148137162>
> :
>
> Indentation problem. Use prettier.
> ------------------------------
>
> On yarn.lock
> <https://github.com/B2B-Services/quickquotes/pull/1#discussion_r1148137827>
> :
>
> How come there are changes to the lock file?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/B2B-Services/quickquotes/pull/1#pullrequestreview-1357554485>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQDOXRKA3CMQ2DUWCG3DPG3W5YTKVANCNFSM6AAAAAAWG4AVY4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-25 14:49 UTC, The-Anomaly submitted a review, later dismissed
Although the indentation issue persists, I'll be approving this PR.
I'll set up a prettier configuration for the project, so there's uniformity.

2023-03-25 15:38 UTC, merged