Error 404
B2B-Services/quickquotes pull request #2
Opened 2023-03-24 18:56 UTC by von-moyo

error 404
error 404(Poor maintenance)

built these two responsive error pages

2023-03-24 23:06 UTC, The-Anomaly requested changes

2023-03-24 23:06 UTC, The-Anomaly commented on src/features/error/error404NotFound/styles.module.scss
> +        border: 1px solid #DDDFE3;
Update this button styling and remove styles that the Button component have accounted for

2023-03-24 23:06 UTC, The-Anomaly commented on src/features/error/error404PoorNetwork/index.tsx
> +            <Button
The button type for this should be "outline" not transparent.

2023-03-24 23:06 UTC, The-Anomaly commented on src/features/error/error404PoorNetwork/styles.module.scss
> +        border: 1px solid #DDDFE3;
Update the styling for this button class and remove attributes that the Button component has accounted for

2023-03-24 23:06 UTC, The-Anomaly commented on src/router/routeBuilder.ts
Undo this change, the path for 404 is a wildcard "*"

2023-03-24 23:06 UTC, The-Anomaly commented on src/router/routes.ts
> +  error404: "/error404",
Remove this route.
A 404, Not found page shouldn't have a dedicated route.

Navigating to any unrecognized route (wrong url) matches the wildcard, "*", hence the page is displayed.

2023-03-24 23:06 UTC, The-Anomaly commented on yarn.lock
The changes to your package.json file affected the lock file.
I'm not expecting any changes here.

2023-03-25 13:15 UTC, von-moyo commented on src/assets/vectors/fileNotFound.png
oh yeah, that, i'll get rid of the png file.

2023-03-25 13:15 UTC, von-moyo commented on src/features/error/error404NotFound/index.tsx
> +          <Button type="transparent" className={styles.errorBackBtn}>
okay, will fix it.

2023-03-25 13:32 UTC, von-moyo commented on package.json
what changes exactly?

2023-03-25 13:47 UTC, von-moyo commented on src/router/routes.ts
> +  error404: "/error404",
oh cool cool.

2023-03-25 15:10 UTC, The-Anomaly submitted a review, later dismissed

2023-03-25 15:42 UTC, merged